# Generated by Django 5.1.4 on 2025-03-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_orden_ordenitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('nequi', 'Nequi'), ('bancolombia', 'Bancolombia')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
